-- =====================================================
-- QUERIES DE TESTE PARA ANALYTICS BUILDER
-- =====================================================

-- 1. QUERY SIMPLES - TESTE BÁSICO (Sempre funciona no Oracle)
SELECT 
    'Janeiro' AS MES,
    100 AS TOTAL,
    50 AS MEDIA
FROM DUAL
UNION ALL
SELECT 'Fevereiro', 150, 75 FROM DUAL
UNION ALL
SELECT 'Março', 200, 100 FROM DUAL
UNION ALL
SELECT 'Abril', 180, 90 FROM DUAL
UNION ALL
SELECT 'Maio', 220, 110 FROM DUAL
UNION ALL
SELECT 'Junho', 250, 125 FROM DUAL;

-- 2. QUERY COM DADOS NUMÉRICOS - PARA GRÁFICOS
SELECT 
    'Setor A' AS SETOR,
    1500 AS FATURAMENTO,
    45 AS PACIENTES
FROM DUAL
UNION ALL
SELECT 'Setor B', 2300, 67 FROM DUAL
UNION ALL
SELECT 'Setor C', 1800, 52 FROM DUAL
UNION ALL
SELECT 'Setor D', 3200, 89 FROM DUAL
UNION ALL
SELECT 'Setor E', 2700, 78 FROM DUAL;

-- 3. QUERY TEMPORAL - PARA ANÁLISE DE TENDÊNCIA
SELECT 
    TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -LEVEL+1), 'MM/YYYY') AS PERIODO,
    ROUND(DBMS_RANDOM.VALUE(100, 500)) AS ATENDIMENTOS,
    ROUND(DBMS_RANDOM.VALUE(50, 150), 2) AS RECEITA
FROM DUAL
CONNECT BY LEVEL <= 12
ORDER BY 1;

-- 4. QUERY COM PERCENTUAIS - PARA GRÁFICO DE PIZZA
SELECT 
    'Particular' AS CONVENIO,
    35 AS PERCENTUAL,
    1500 AS VALOR_TOTAL
FROM DUAL
UNION ALL
SELECT 'Unimed', 40, 2000 FROM DUAL
UNION ALL
SELECT 'SUS', 15, 800 FROM DUAL
UNION ALL
SELECT 'Outros', 10, 500 FROM DUAL;

-- 5. QUERY COMPLETA - DASHBOARD EXECUTIVO
SELECT 
    TO_CHAR(TRUNC(SYSDATE) - LEVEL + 1, 'DD/MM') AS DIA,
    ROUND(DBMS_RANDOM.VALUE(50, 150)) AS CONSULTAS,
    ROUND(DBMS_RANDOM.VALUE(10, 30)) AS INTERNACOES,
    ROUND(DBMS_RANDOM.VALUE(5000, 15000), 2) AS FATURAMENTO,
    ROUND(DBMS_RANDOM.VALUE(70, 95), 1) AS TAXA_OCUPACAO
FROM DUAL
CONNECT BY LEVEL <= 30
ORDER BY 1;

-- =====================================================
-- QUERIES REAIS DO TASY (EXEMPLOS)
-- Substitua pelas tabelas do seu sistema
-- =====================================================

-- 6. OCUPAÇÃO DE LEITOS (Exemplo - Ajuste conforme suas tabelas)
/*
SELECT 
    TO_CHAR(DT_REFERENCIA, 'DD/MM/YYYY') AS DATA,
    COUNT(DISTINCT CD_LEITO) AS LEITOS_OCUPADOS,
    (SELECT COUNT(*) FROM LEITOS WHERE IE_ATIVO = 'S') AS TOTAL_LEITOS,
    ROUND((COUNT(DISTINCT CD_LEITO) * 100.0 / 
          (SELECT COUNT(*) FROM LEITOS WHERE IE_ATIVO = 'S')), 2) AS TAXA_OCUPACAO
FROM OCUPACAO_LEITO
WHERE DT_REFERENCIA >= TRUNC(SYSDATE) - 30
GROUP BY DT_REFERENCIA
ORDER BY 1
FETCH FIRST 200 ROWS ONLY;
*/

-- 7. ATENDIMENTOS POR ESPECIALIDADE (Exemplo)
/*
SELECT 
    DS_ESPECIALIDADE AS ESPECIALIDADE,
    COUNT(*) AS TOTAL_ATENDIMENTOS,
    AVG(TEMPO_ATENDIMENTO) AS TEMPO_MEDIO_MINUTOS
FROM AGENDA_CONSULTA AC
JOIN MEDICOS M ON AC.CD_MEDICO = M.CD_MEDICO
WHERE DT_AGENDA >= TRUNC(ADD_MONTHS(SYSDATE, -3))
AND IE_STATUS_AGENDA = 'A' -- Atendido
GROUP BY DS_ESPECIALIDADE
ORDER BY 2 DESC
FETCH FIRST 10 ROWS ONLY;
*/

-- 8. FATURAMENTO POR CONVÊNIO (Exemplo)
/*
SELECT 
    DS_CONVENIO,
    COUNT(*) AS QTD_ATENDIMENTOS,
    SUM(VL_TOTAL_CONTA) AS FATURAMENTO_TOTAL,
    AVG(VL_TOTAL_CONTA) AS TICKET_MEDIO
FROM CONTAS_HOSPITALARES
WHERE DT_FATURAMENTO >= TRUNC(ADD_MONTHS(SYSDATE, -1))
GROUP BY DS_CONVENIO
ORDER BY 3 DESC
FETCH FIRST 200 ROWS ONLY;
*/

-- =====================================================
-- DICAS DE USO:
-- =====================================================
-- 1. Sempre use FETCH FIRST 200 ROWS ONLY para limitar dados
-- 2. Use TO_CHAR para formatar datas como texto
-- 3. Use ROUND para limitar casas decimais
-- 4. Sempre ordene os resultados (ORDER BY)
-- 5. Use aliases claros (AS MES, AS TOTAL, etc.)
-- 6. Evite queries muito complexas - faça agregações no SQL
-- 7. Teste a query antes no SQL Developer
